### ISSUE TITLE
Suspicious behavior around "or" with arp/icmp

### ISSUE THREAD

**Issue by lukego** [Igalia/pflua#178]
I am seeing strange behavior with pflang filters on snabbnfv with snabbswitch master.

The issue is that ARP packets are accepted with these filters:

- arp
- arp or icmp

but are rejected with this filter:

- icmp or arp

whereas I expect them to be accepted in every case.

Can you suggest how to troubleshoot this?

**Comment by lukego** [comment]
NB: I also see this behavior on current master (e7d011b46d0eafeb3bcdc35d8713a7d4e3cbaa11).

**Comment by eugeneia** [comment]
I checked this in Wireshark which behaves like Luke expected. Quick feedback would be appreciated as we plan to do a release including pflua like any time now.

**Comment by andywingo** [comment]
Morning :) Am back from holidays, will take a look.

**Comment by andywingo** [comment]
As a note on how to trouble-shoot something like this in the future, it's usually not worth checking this in Wireshark; Wireshark has its own filter language.  At least, the bar at the top for filtering is not the same thing as pflang though it is similar.  I don't know if it supports pflang somewhere else.

The first step in troubleshooting is to see if the behavior is different with the BPF pipeline.  Pass the "bpf=true" option to pf.compile().  That will compile the filter to BPF bytecode using libpcap, but then compile the BPF to Lua using pflua.  If the behavior is different, it's likely is that the BPF pipeline is doing the right thing, and that you've found a bug in the "native" pflang pipeline in pflua.

(It could be at this point though that you've found (1) a bug in pflua's BPF pipeline, (2) in libpcap's bytecode optimizer (which is on by default), or (3) in some other part of libpcap.  Historically speaking we haven't found any bugs in (1) in a long time, but we have found bugs in (2) and rarely in (3).  But again, a difference in behavior between the BPF pipeline and the "native" pipeline in pflua usually indicates a "native" pipeline bug.)

So, you have a native pipeline bug.  It could be in the parser, the expander, the optimizer, or the code generator.  Since the parse succeeded it's probably not in the parser.  We haven't found any bugs in the code generator in a long time so probably it's not there either.  So either it's in the expander, which lowers terms like "arp" to e.g. "length >= 14 and ether[12:2] == 2054", or in the optimizer.  Easiest thing to try is to pass "optimize=false" as a pf.compile option.  If the behavior is different optimized or not, then you found an optimizer bug.  Otherwise it's probably an expander bug.  That's the troubleshooting procedure.  Now, I will descend from the meta-level and work on this bug :)

**Comment by lukego** [comment]
Thanks very much for explaining that, Andy!

**Comment by andywingo** [comment]
The oddly-named tools/pipe-lua-libpcap-match tool can do some automated comparisons of match results on different pipelines (native pflua, pflua via libpcap-compiled bpf, and libpcap-interpreted bpf).  It can also try with or without optimization.  Using that tool in #180 shows that it's an optimizer bug.

Just FYI and for other pflua hackers :)  To troubleshoot the optimizer, it's kinda hard but it's possible to narrow things down a bit.  There are three major optimizations that the high-level optimizer does: condition folding, range inference, and length check hoisting.  Each is followed by a generic cleanup pass ("simplify"), and the whole thing is iterated to a fixed point as they are all shrinking optimizations and so it will terminate.  See https://github.com/Igalia/pflua/blob/master/src/pf/optimize.lua#L726.  To see if the bug is in one of these passes, just comment out the line corresponding to the pass and re-run.  There aren't nice command-line options for this, unfortunately.  Doing this, I find that the bug is in the length-check hoisting pass (lhoist).

**Comment by andywingo** [comment]
Fixed in https://github.com/Igalia/pflua/commit/86219cbdca4a56797e47628fdfa21a9e128b6054, I think.  Thanks for the report!

**Comment by lukego** [comment]
That works, thanks!

**Comment by kbara** [comment]
FYI, the pipe-* tools are now merged into one tool, and known as 'pflua-pipelines-match'.
